<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Best employee group' => 'Grupo del mejor empleado',
    'Contact and tracking' => 'Contacto y seguimiento',
    'Evolution Title' => '',
    'Feedback' => '<em>Feedback</em>',
    'Home' => 'Inicio',
    'ID' => 'ID',
    'Questions' => 'Cuestiones',
    'Goal' => 'Objetivo',
    'Language' => 'Idioma',
    'Met Expectation Title' => '',
    'Required data' => 'Datos requeridos',
    'Source' => 'Fuente',
    'Apartment' => 'Apartamento',
    'Are you sure you want to delete this item?' => '¿Está seguro de que desea borrar este elemento?',
    'Avg.' => 'Media',
    'Bad things' => 'Aspectos negativos',
    'Best employee' => 'Mejor empleado',
    'Change periods' => 'Cambiar períodos',
    'Checkout date' => 'Fecha de salida',
    'Code' => 'Código',
    'Count' => 'Cuenta',
    'Country ID' => 'ID País',
    'Create' => 'Crear',
    'Create Survey' => 'Crear Cuestionario',
    'Current month' => 'Mes actual',
    'Current year' => 'Año actual',
    'Delete' => 'Eliminar',
    'Department' => 'Departamento',
    'Department Name' => 'Nombre de departamento',
    'Enter checkout date' => 'Introduzca la fecha de salida',
    'Global score' => 'Puntuación global',
    'Good things' => 'Aspectos positivos',
    'Group' => 'Grupo',
    'Group ID' => 'ID grupo',
    'Groups' => 'Grupos',
    'Guest address' => 'Dirección del huésped',
    'Guest country' => 'País del huésped',
    'Guest email' => 'Email del huésped',
    'Guest name' => 'Nombre del huésped',
    'How did we meet your expectations?' => '¿Cómo hemos cumplido con sus expectativas?',
    'If you are a repeating guest, how does Riosol evolve?' => 'Si repite como huésped, ¿cómo evoluciona riosol? ',
    'Index' => 'Índice',
    'Language Code' => 'Código de idioma',
    'List' => 'Lista',
    'Name' => 'Nombre',
    'Period' => 'Período',
    'Question' => 'Cuestión',
    'Question ID' => 'ID Cuestión',
    'Reset' => 'Restaurar',
    'Save' => 'Guardar',
    'Score' => 'Puntuación',
    'Search' => 'Buscar',
    'Selectable questions' => 'Cuestiones elegibles',
    'Selected into this group' => 'Seleccionadas en este grupo',
    'Smiley groups' => 'Grupos de <em>smileys</em>',
    'Smiley questions' => 'Cuestiones de <em>smileys</em>',
    'Suggestions' => 'Sugerencias',
    'Summary' => 'Resumen',
    'Survey ID' => 'ID Cuestionario',
    'Surveys' => 'Cuestionarios',
    'Title' => 'Título',
    'Touroperator' => 'Touroperador',
    'Translation' => 'Traducción',
    'Update' => 'Actualizar',
    'Update {modelClass}: ' => 'Actualizar {modelClass}:',
    'Why did you choose our hotel?' => '¿Por qué eligió nuestro hotel?',
];
