<?php

use yii\db\Migration;
use app\models\Country;
use app\models\Question;
use app\models\Group;

class m170210_142107_init extends Migration {
    public function safeUp() {
        $this->createTable('language', [
            'code' => $this->string(2) . ' primary key',
            'name' => $this->string(16)
        ]);
        $this->createTable('met_expectation', [
            'title' => $this->string(48) . ' primary key',
            'index' => $this->smallInteger(1),
            'score' => $this->smallInteger(1),
        ]);
        $this->createTable('met_expectation_translation', [
            'id' => $this->primaryKey(),
            'met_expectation_title' => $this->string(48),
            'language_code' => $this->string(2),
            'translation' => $this->string(48),
        ]);
        $this->addForeignKey(
            'fk-met_expectation_translation-met_expectation_title',
            'met_expectation_translation',
            'met_expectation_title',
            'met_expectation',
            'title'
        );
        $this->addForeignKey(
            'fk-met_expectation_translation-language_code',
            'met_expectation_translation',
            'language_code',
            'language',
            'code'
        );
        $this->createTable('election', [
            'title' => $this->string(48) . ' primary key',
            'index' => $this->smallInteger(1)
        ]);
        $this->createTable('election_translation', [
            'id' => $this->primaryKey(),
            'election_title' => $this->string(48),
            'language_code' => $this->string(2),
            'translation' => $this->string(48),
        ]);
        $this->addForeignKey(
            'fk-election_translation-election_title',
            'election_translation',
            'election_title',
            'election',
            'title'
        );
        $this->addForeignKey(
            'fk-election_translation-language_code',
            'election_translation',
            'language_code',
            'language',
            'code'
        );
        $this->createTable('evolution', [
            'title' => $this->string(48) . ' primary key',
            'index' => $this->smallInteger(1),
            'score' => $this->smallInteger(1),
        ]);
        $this->createTable('evolution_translation', [
            'id' => $this->primaryKey(),
            'evolution_title' => $this->string(48),
            'language_code' => $this->string(2),
            'translation' => $this->string(48),
        ]);
        $this->addForeignKey(
            'fk-evolution_translation-evolution_title',
            'evolution_translation',
            'evolution_title',
            'evolution',
            'title'
        );
        $this->addForeignKey(
            'fk-evolution_translation-language_code',
            'evolution_translation',
            'language_code',
            'language',
            'code'
        );
        $this->createTable('country', [
            'id' => $this->primaryKey(),
            'name' => $this->string(48)
        ]);
        $this->createTable('country_translation', [
            'id' => $this->primaryKey(),
            'language_code' => $this->string(2),
            'country_id' => $this->integer(),
            'translation' => $this->string(48)
        ]);
        $this->addForeignKey(
            'fk-country_translation-country_id',
            'country_translation',
            'country_id',
            'country',
            'id'
        );
        $this->addForeignKey(
            'fk-country_translation-language_code',
            'country_translation',
            'language_code',
            'language',
            'code'
        );
        $this->createTable('touroperator', [
            'name' => $this->string(48) . ' primary key',
        ]);
        $this->createTable('department', [
            'name' => $this->string(32) . ' primary key',
            'index' => $this->smallInteger(1),
        ]);
        $this->createTable('department_translation', [
            'id' => $this->primaryKey(),
            'language_code' => $this->string(2),
            'department_name' => $this->string(32),
            'translation' => $this->string(32)
        ]);
        $this->addForeignKey(
            'fk-department_translation-department_name',
            'department_translation',
            'department_name',
            'department',
            'name'
        );
        $this->addForeignKey(
            'fk-department_translation-language_code',
            'department_translation',
            'language_code',
            'language',
            'code'
        );
        $this->createTable('survey', [
            'id' => $this->primaryKey(),
            'checkout_date' => $this->date()->notNull(),
            'apartment' => $this->string(5)->notNull(),
            'global_score' => $this->smallInteger(1)->notNull(),
            'election_title' => $this->string(48)->notNull(),
            'guest_name' => $this->string(48),
            'guest_country_id' => $this->integer(),
            'guest_email' => $this->string(128),
            'guest_address' => $this->string(),
            'touroperator_name' => $this->string(48),
            'best_employee_name' => $this->string(48),
            'best_employee_department_name' => $this->string(32),
            'met_expectation_title' => $this->string(48),
            'evolution_title' => $this->string(48),
            'good_things' => $this->string(128),
            'bad_things' => $this->string(128),
            'suggestions' => $this->text()
        ]);
        $this->addForeignKey(
            'fk-survey-election_title',
            'survey',
            'election_title',
            'election',
            'title'
        );
        $this->addForeignKey(
            'fk-survey-guest_country_id',
            'survey',
            'guest_country_id',
            'country',
            'id'
        );
        $this->addForeignKey(
            'fk-survey-touroperator_name',
            'survey',
            'touroperator_name',
            'touroperator',
            'name'
        );
        $this->addForeignKey(
            'fk-survey-best_employee_department_name',
            'survey',
            'best_employee_department_name',
            'department',
            'name'
        );
        $this->addForeignKey(
            'fk-survey-met_expectation_title',
            'survey',
            'met_expectation_title',
            'met_expectation',
            'title'
        );
        $this->addForeignKey(
            'fk-survey-evolution_title',
            'survey',
            'evolution_title',
            'evolution',
            'title'
        );
        $this->createTable('question', [
            'id' => $this->primaryKey(),
            'index' => $this->smallInteger(1),
            'department_name' => $this->string(32)->notNull(),
            'title' => $this->string(32)
        ]);
        $this->createIndex('question-index-department_name-uidx', 'question', ['index', 'department_name'], true);
        $this->createIndex('question-title-department_name-uidx', 'question', ['title', 'department_name'], true);
        $this->addForeignKey(
            'fk-question-department_name',
            'question',
            'department_name',
            'department',
            'name'
        );
        $this->createTable('question_translation', [
            'id' => $this->primaryKey(),
            'language_code' => $this->string(2),
            'question_id' => $this->integer(),
            'translation' => $this->string(32)
        ]);
        $this->addForeignKey(
            'fk-question_translation-question_id',
            'question_translation',
            'question_id',
            'question',
            'id'
        );
        $this->addForeignKey(
            'fk-question_translation-language_code',
            'question_translation',
            'language_code',
            'language',
            'code'
        );
        $this->createTable('answer', [
            'id' => $this->primaryKey(),
            'question_id' => $this->integer()->notNull(),
            'survey_id' => $this->integer()->notNull(),
            'score' => $this->smallInteger(1),
        ]);
        $this->addForeignKey(
            'fk-answer-question_id',
            'answer',
            'question_id',
            'question',
            'id'
        );
        $this->addForeignKey(
            'fk-answer-survey_id',
            'answer',
            'survey_id',
            'survey',
            'id'
        );
        $this->createTable('grp', [
            'id' => $this->primaryKey(),
            'name' => $this->string(32)->unique(),
            'index' => $this->smallInteger(1)
        ]);
        $this->createTable('group_translation', [
            'id' => $this->primaryKey(),
            'language_code' => $this->string(2),
            'group_id' => $this->integer(),
            'translation' => $this->string(32)
        ]);
        $this->addForeignKey(
            'fk-group_translation-group_id',
            'group_translation',
            'group_id',
            'grp',
            'id'
        );
        $this->addForeignKey(
            'fk-group_translation-language_code',
            'group_translation',
            'language_code',
            'language',
            'code'
        );
        $this->createTable('group_question', [
            'id' => $this->primaryKey(),
            'question_id' => $this->integer(),
            'group_id' => $this->integer()
        ]);
        $this->addForeignKey(
            'fk-group_question-question_id',
            'group_question',
            'question_id',
            'question',
            'id'
        );
        $this->addForeignKey(
            'fk-group_question-group_id',
            'group_question',
            'group_id',
            'grp',
            'id'
        );
        $this->batchInsert('language', ['code', 'name'], [
	    ['es', 'Español' ],
	    ['en', 'English' ],
	    ['de', 'Deutsch' ],
	    ['no', 'Norsk' ],
	    ['ru', 'Pу́сский']
        ]);
        $this->batchInsert('met_expectation', ['index', 'score', 'title'], [
            [0, 2, 'Better than expected'],
            [1, 1, 'As expected'],
            [2, 0, 'Worse than expected']
        ]);
        $this->batchInsert('met_expectation_translation', ['met_expectation_title', 'language_code', 'translation'], [
            ['Better than expected', 'es', 'Mejor de lo esperado'],
            ['As expected', 'es', 'Como se esperaba'],
            ['Worse than expected', 'es', 'Peor de lo esperado']
        ]);
        $this->batchInsert('evolution', ['index', 'score', 'title'], [
            [0, 2, 'Has improved'],
            [1, 1, 'Maintains its level'],
            [2, 0, 'Has worsened']
        ]);
        $this->batchInsert('evolution_translation', ['evolution_title', 'language_code', 'translation'], [
            ['Has improved', 'es', 'Ha mejorado'],
            ['Maintains its level', 'es', 'Mantiene su nivel'],
            ['Has worsened', 'es', 'Ha empeorado']
        ]);
        $this->batchInsert('election', ['index', 'title'], [
            [0, 'Previous stay'],
            [1, 'Recommendation'],
            [2, 'Travel agency'],
            [3, 'Tour operator advertising'],
            [4, 'Internet'],
            [5, 'Other']
        ]);
        $this->batchInsert('election_translation', ['election_title', 'language_code', 'translation'], [
            ['Previous stay', 'es', 'Estancia anterior'],
            ['Recommendation', 'es', 'Recomendación'],
            ['Travel agency', 'es', 'Agencia de viajes'],
            ['Tour operator advertising', 'es', 'Publicidad del tour-operador'],
            ['Internet', 'es', 'Internet'],
            ['Other', 'es', 'Otros']
        ]);
        $this->batchInsert('department', ['index', 'name'], [
            [0, 'Reception'],
            [1, 'Restaurant'],
            [2, 'Pool bar / Lounge bar'],
            [3, 'Restaurant "El Mirador"'],
            [4, 'Apartments'],
            [5, 'Maintenance'],
            [6, 'Animation'],
            [7, 'Swimming pools'],
            [8, 'Sports']
        ]);
        $this->batchInsert('department_translation', ['language_code', 'department_name', 'translation'], [
            ['es', 'Reception', 'Recepción'],
            ['es', 'Restaurant', 'Restaurante'],
            ['es', 'Pool bar / Lounge bar', 'Bar piscina / Bar salón'],
            ['es', 'Restaurant "El Mirador"', 'Restaurante "El Mirador"'],
            ['es', 'Apartments', 'Apartamentos'],
            ['es', 'Maintenance', 'Servicio técnico'],
            ['es', 'Animation', 'Animación'],
            ['es', 'Swimming pools', 'Piscinas'],
            ['es', 'Sports', 'Animación']
        ]);
        $this->batchInsert('question', ['index', 'department_name', 'title'], [
            [0, 'Reception', 'Courtesy'], 
            [1, 'Reception', 'Efficiency'], 
            [2, 'Reception', 'Languages'], 
            [0, 'Restaurant', 'Breakfast quality'], 
            [1, 'Restaurant', 'Breakfast variety'], 
            [2, 'Restaurant', 'Breakfast service'], 
            [3, 'Restaurant', 'Dinner quality'], 
            [4, 'Restaurant', 'Dinner variety'], 
            [5, 'Restaurant', 'Dinner service'], 
            [0, 'Pool bar / Lounge bar', 'Food'], 
            [1, 'Pool bar / Lounge bar', 'Service'], 
            [2, 'Pool bar / Lounge bar', 'Atmosphere'], 
            [0, 'Restaurant "El Mirador"', 'Food'], 
            [1, 'Restaurant "El Mirador"', 'Service'], 
            [0, 'Apartments', 'Comfort'], 
            [1, 'Apartments', 'Equipment'], 
            [2, 'Apartments', 'Maintenance'], 
            [3, 'Apartments', 'Cleanliness'], 
            [0, 'Maintenance', 'Kindness'], 
            [1, 'Maintenance', 'Efficiency'], 
            [0, 'Animation', 'Professional shows'], 
            [1, 'Animation', 'Activities'], 
            [2, 'Animation', 'Mini-club'], 
            [3, 'Animation', 'Entertainer'], 
            [0, 'Swimming pools', 'Service'], 
            [1, 'Swimming pools', 'Cleanliness'], 
            [0, 'Sports', 'Tennis'], 
            [1, 'Sports', 'Gymnasium'] 
        ]);
        $this->batchInsert('grp', ['name', 'index'], [
            ['Reception', 0],
            ['Bar / Restaurant', 1],
            ['Kitchen', 2],
            ['Cleaning', 3],
            ['Maintenance', 4],
            ['Entertaining', 5],
            ['Swimming pools', 6]
        ]);
        $reception_courtesy_id = Question::findOne(['title' => 'Courtesy', 'department_name' => 'Reception'])->id;
        $i = $reception_courtesy_id;
        $reception_group_id = Group::findOne(['name' => 'Reception'])->id;
        $this->batchInsert('group_question', ['question_id', 'group_id'], [
            [$i++, $reception_group_id],
            [$i++, $reception_group_id],
            [$i++, $reception_group_id],
            [$i++, $reception_group_id + 1],
            [$i++, $reception_group_id + 1],
            [$i++, $reception_group_id + 1],
            [$i++, $reception_group_id + 1],
            [$i++, $reception_group_id + 1],
            [$i++, $reception_group_id + 1],
            [$i++, $reception_group_id + 1],
            [$i++, $reception_group_id + 1],
            [$i++, $reception_group_id + 1],
            [$i++, $reception_group_id + 1],
            [$i++, $reception_group_id + 1],
            [$reception_courtesy_id + 3, $reception_group_id + 2],
            [$reception_courtesy_id + 4, $reception_group_id + 2],
            [$reception_courtesy_id + 5, $reception_group_id + 2],
            [$reception_courtesy_id + 6, $reception_group_id + 2],
            [$reception_courtesy_id + 7, $reception_group_id + 2],
            [$reception_courtesy_id + 8, $reception_group_id + 2],
            [$reception_courtesy_id + 9, $reception_group_id + 2],
            [$reception_courtesy_id + 12, $reception_group_id + 2],
            [$reception_courtesy_id + 16, $reception_group_id + 3],
            [$reception_courtesy_id + 17, $reception_group_id + 3],
            [$reception_courtesy_id + 25, $reception_group_id + 3],
            [$reception_courtesy_id + 15, $reception_group_id + 4],
            [$reception_courtesy_id + 16, $reception_group_id + 4],
            [$reception_courtesy_id + 17, $reception_group_id + 4],
            [$reception_courtesy_id + 18, $reception_group_id + 4],
            [$reception_courtesy_id + 27, $reception_group_id + 4],
            [$reception_courtesy_id + 11, $reception_group_id + 5],
            [$reception_courtesy_id + 20, $reception_group_id + 5],
            [$reception_courtesy_id + 21, $reception_group_id + 5],
            [$reception_courtesy_id + 22, $reception_group_id + 5],
            [$reception_courtesy_id + 23, $reception_group_id + 5],
            [$reception_courtesy_id + 24, $reception_group_id + 6],
            [$reception_courtesy_id + 25, $reception_group_id + 6],
            [$reception_courtesy_id + 24, $reception_group_id + 6]
        ]);
        $j = $reception_group_id;
        $this->batchInsert('group_translation', ['language_code', 'group_id', 'translation'], [
            ['es', $j++, 'Recepción'],
            ['es', $j++, 'Bar / Restaurante'],
            ['es', $j++, 'Cocina'],
            ['es', $j++, 'Limpieza'],
            ['es', $j++, 'Mantenimiento'],
            ['es', $j++, 'Animación'],
            ['es', $j++, 'Piscinas']
        ]);
        $i = $reception_courtesy_id;
        $this->batchInsert('question_translation', ['language_code', 'question_id', 'translation'], [
            ['es', $i++, 'Cortesía'],
            ['es', $i++, 'Eficacia'],
            ['es', $i++, 'Idiomas'],
            ['es', $i++, 'Desayunos calidad'],
            ['es', $i++, 'Desayunos variedad'],
            ['es', $i++, 'Desayunos servicio'],
            ['es', $i++, 'Cenas calidad'],
            ['es', $i++, 'Cenas variedad'],
            ['es', $i++, 'Cenas servicio'],
            ['es', $i++, 'Comida'],
            ['es', $i++, 'Servicio'],
            ['es', $i++, 'Ambiente'],
            ['es', $i++, 'Comida'],
            ['es', $i++, 'Servicio'],
            ['es', $i++, 'Confort'],
            ['es', $i++, 'Equipamiento'],
            ['es', $i++, 'Mantenimiento'],
            ['es', $i++, 'Limpieza'],
            ['es', $i++, 'Amabilidad'],
            ['es', $i++, 'Eficacia'],
            ['es', $i++, 'Shows profesionales'],
            ['es', $i++, 'Actividades'],
            ['es', $i++, 'Mini-club'],
            ['es', $i++, 'Animador'],
            ['es', $i++, 'Servicio'],
            ['es', $i++, 'Limpieza'],
            ['es', $i++, 'Tenis'],
            ['es', $i++, 'Gimnasio']
        ]);
        $this->batchInsert('country', ['name'], [
            ['Afghanistan'],
            ['Albania'],
            ['Algeria'],
            ['Andorra'],
            ['Angola'],
            ['Antigua and Barbuda'],
            ['Argentina'],
            ['Armenia'],
            ['Australia'],
            ['Austria'],
            ['Azerbaijan'],
            ['Bahamas, The'],
            ['Bahrain'],
            ['Bangladesh'],
            ['Barbados'],
            ['Belarus'],
            ['Belgium'],
            ['Belize'],
            ['Benin'],
            ['Bhutan'],
            ['Bolivia'],
            ['Bosnia and Herzegovina'],
            ['Botswana'],
            ['Brazil'],
            ['Brunei'],
            ['Bulgaria'],
            ['Burkina Faso'],
            ['Burundi'],
            ['Cambodia'],
            ['Cameroon'],
            ['Canada'],
            ['Cape Verde'],
            ['Central African Republic'],
            ['Chad'],
            ['Chile'],
            ['China'],
            ['Colombia'],
            ['Comoros'],
            ['Congo, Democratic Republic of the'],
            ['Congo, Republic of the'],
            ['Costa Rica'],
            ['Croatia'],
            ['Cuba'],
            ['Cyprus'],
            ['Czech Republic'],
            ['Denmark'],
            ['Djibouti'],
            ['Dominica'],
            ['Dominican Republic'],
            ['East Timor'],
            ['Ecuador'],
            ['Egypt'],
            ['El Salvador'],
            ['Equatorial Guinea'],
            ['Eritrea'],
            ['Estonia'],
            ['Ethiopia'],
            ['Fiji'],
            ['Finland'],
            ['France'],
            ['Gabon'],
            ['Gambia, The'],
            ['Georgia'],
            ['Germany'],
            ['Ghana'],
            ['Greece'],
            ['Grenada'],
            ['Guatemala'],
            ['Guinea'],
            ['Guinea-Bissau'],
            ['Guyana'],
            ['Haiti'],
            ['Honduras'],
            ['Hungary'],
            ['Iceland'],
            ['India'],
            ['Indonesia'],
            ['Iran'],
            ['Iraq'],
            ['Ireland'],
            ['Israel'],
            ['Italy'],
            ['Ivory Coast'],
            ['Jamaica'],
            ['Japan'],
            ['Jordan'],
            ['Kazakhstan'],
            ['Kenya'],
            ['Kiribati'],
            ['Korea, North'],
            ['Korea, South'],
            ['Kuwait'],
            ['Kyrgyzstan'],
            ['Laos'],
            ['Latvia'],
            ['Lebanon'],
            ['Lesotho'],
            ['Liberia'],
            ['Libya'],
            ['Liechtenstein'],
            ['Lithuania'],
            ['Luxembourg'],
            ['Macedonia'],
            ['Madagascar'],
            ['Malawi'],
            ['Malaysia'],
            ['Maldives'],
            ['Mali'],
            ['Malta'],
            ['Marshall Islands'],
            ['Mauritania'],
            ['Mauritius'],
            ['Mexico'],
            ['Micronesia'],
            ['Moldova'],
            ['Monaco'],
            ['Mongolia'],
            ['Montenegro'],
            ['Morocco'],
            ['Mozambique'],
            ['Myanmar'],
            ['Namibia'],
            ['Nauru'],
            ['Nepal'],
            ['Netherlands'],
            ['New Zealand'],
            ['Nicaragua'],
            ['Niger'],
            ['Nigeria'],
            ['Norway'],
            ['Oman'],
            ['Pakistan'],
            ['Palau'],
            ['Palestine'],
            ['Panama'],
            ['Papua New Guinea'],
            ['Paraguay'],
            ['Peru'],
            ['Philippines'],
            ['Poland'],
            ['Portugal'],
            ['Qatar'],
            ['Romania'],
            ['Russia'],
            ['Rwanda'],
            ['Saint Kitts and Nevis'],
            ['Saint Lucia'],
            ['Saint Vincent and the Grenadines'],
            ['Samoa'],
            ['San Marino'],
            ['São Tomé and Príncipe'],
            ['Saudi Arabia'],
            ['Senegal'],
            ['Serbia'],
            ['Seychelles'],
            ['Sierra Leone'],
            ['Singapore'],
            ['Slovakia'],
            ['Slovenia'],
            ['Solomon Islands'],
            ['Somalia'],
            ['South Africa'],
            ['South Sudan'],
            ['Spain'],
            ['Sri Lanka'],
            ['Sudan'],
            ['Suriname'],
            ['Swaziland'],
            ['Sweden'],
            ['Switzerland'],
            ['Syria'],
            ['Tajikistan'],
            ['Tanzania'],
            ['Thailand'],
            ['Togo'],
            ['Tonga'],
            ['Trinidad and Tobago'],
            ['Tunisia'],
            ['Turkey'],
            ['Turkmenistan'],
            ['Tuvalu'],
            ['Uganda'],
            ['Ukraine'],
            ['United Arab Emirates'],
            ['United Kingdom'],
            ['United States'],
            ['Uruguay'],
            ['Uzbekistan'],
            ['Vanuatu'],
            ['Vatican City'],
            ['Venezuela'],
            ['Vietnam'],
            ['Yemen'],
            ['Zambia'],
            ['Zimbabwe']
        ]);
        $afghan_id = Country::findOne(['name' => 'Afghanistan'])->id;
        $i = $afghan_id;
        $this->batchInsert('country_translation', ['language_code', 'country_id', 'translation'], [
             ['es', $i++, 'Afganistán'],
             ['es', $i++, 'Albania'],
             ['es', $i++, 'Argelia'],
             ['es', $i++, 'Andorra'],
             ['es', $i++, 'Angola'],
             ['es', $i++, 'Antigua y Barbuda'],
             ['es', $i++, 'Argentina'],
             ['es', $i++, 'Armenia'],
             ['es', $i++, 'Australia'],
             ['es', $i++, 'Austria'],
             ['es', $i++, 'Azerbaiyán'],
             ['es', $i++, 'Bahamas, el'],
             ['es', $i++, 'Bahrein'],
             ['es', $i++, 'Bangladesh'],
             ['es', $i++, 'Barbados'],
             ['es', $i++, 'Bielorrusia'],
             ['es', $i++, 'Bélgica'],
             ['es', $i++, 'Belice'],
             ['es', $i++, 'Benin'],
             ['es', $i++, 'Bután'],
             ['es', $i++, 'Bolivia'],
             ['es', $i++, 'Bosnia y Herzegovina'],
             ['es', $i++, 'Botswana'],
             ['es', $i++, 'Brasil'],
             ['es', $i++, 'Brunei'],
             ['es', $i++, 'Bulgaria'],
             ['es', $i++, 'Burkina Faso'],
             ['es', $i++, 'Burundi'],
             ['es', $i++, 'Camboya'],
             ['es', $i++, 'Camerún'],
             ['es', $i++, 'Canadá'],
             ['es', $i++, 'Cabo Verde'],
             ['es', $i++, 'República Centroafricana'],
             ['es', $i++, 'Chad'],
             ['es', $i++, 'Chile'],
             ['es', $i++, 'China'],
             ['es', $i++, 'Colombia'],
             ['es', $i++, 'Comoras'],
             ['es', $i++, 'Congo, República Democrática del'],
             ['es', $i++, 'Congo, República del'],
             ['es', $i++, 'Costa Rica'],
             ['es', $i++, 'Croacia'],
             ['es', $i++, 'Cuba'],
             ['es', $i++, 'Chipre'],
             ['es', $i++, 'República Checa'],
             ['es', $i++, 'Dinamarca'],
             ['es', $i++, 'Djibouti'],
             ['es', $i++, 'Dominica'],
             ['es', $i++, 'República Dominicana'],
             ['es', $i++, 'Timor Oriental'],
             ['es', $i++, 'Ecuador'],
             ['es', $i++, 'Egipto'],
             ['es', $i++, 'El Salvador'],
             ['es', $i++, 'Guinea Ecuatorial'],
             ['es', $i++, 'Eritrea'],
             ['es', $i++, 'Estonia'],
             ['es', $i++, 'Etiopía'],
             ['es', $i++, 'Fiyi'],
             ['es', $i++, 'Finlandia'],
             ['es', $i++, 'Francia'],
             ['es', $i++, 'Gabón'],
             ['es', $i++, 'Gambia, el'],
             ['es', $i++, 'Georgia'],
             ['es', $i++, 'Alemania'],
             ['es', $i++, 'Ghana'],
             ['es', $i++, 'Grecia'],
             ['es', $i++, 'Granada'],
             ['es', $i++, 'Guatemala'],
             ['es', $i++, 'Guinea'],
             ['es', $i++, 'Guinea-Bissau'],
             ['es', $i++, 'Guayana'],
             ['es', $i++, 'Haití'],
             ['es', $i++, 'Honduras'],
             ['es', $i++, 'Hungría'],
             ['es', $i++, 'Islandia'],
             ['es', $i++, 'India'],
             ['es', $i++, 'Indonesia'],
             ['es', $i++, 'Corrí'],
             ['es', $i++, 'Irak'],
             ['es', $i++, 'Irlanda'],
             ['es', $i++, 'Israel'],
             ['es', $i++, 'Italia'],
             ['es', $i++, 'Costa de Marfil'],
             ['es', $i++, 'Jamaica'],
             ['es', $i++, 'Japón'],
             ['es', $i++, 'Jordán'],
             ['es', $i++, 'Kazajstán'],
             ['es', $i++, 'Kenia'],
             ['es', $i++, 'Kiribati'],
             ['es', $i++, 'Corea del Norte'],
             ['es', $i++, 'Corea del Sur'],
             ['es', $i++, 'Kuwait'],
             ['es', $i++, 'Kirguistán'],
             ['es', $i++, 'Laos'],
             ['es', $i++, 'Letonia'],
             ['es', $i++, 'Líbano'],
             ['es', $i++, 'Lesoto'],
             ['es', $i++, 'Liberia'],
             ['es', $i++, 'Libia'],
             ['es', $i++, 'Liechtenstein'],
             ['es', $i++, 'Lituania'],
             ['es', $i++, 'Luxemburgo'],
             ['es', $i++, 'macedonia'],
             ['es', $i++, 'Madagascar'],
             ['es', $i++, 'Malawi'],
             ['es', $i++, 'Malasia'],
             ['es', $i++, 'Maldivas'],
             ['es', $i++, 'Mali'],
             ['es', $i++, 'Malta'],
             ['es', $i++, 'Islas Marshall'],
             ['es', $i++, 'Mauritania'],
             ['es', $i++, 'Mauricio'],
             ['es', $i++, 'Méjico'],
             ['es', $i++, 'Micronesia'],
             ['es', $i++, 'Moldavia'],
             ['es', $i++, 'Mónaco'],
             ['es', $i++, 'Mongolia'],
             ['es', $i++, 'Montenegro'],
             ['es', $i++, 'Marruecos'],
             ['es', $i++, 'Mozambique'],
             ['es', $i++, 'Myanmar'],
             ['es', $i++, 'Namibia'],
             ['es', $i++, 'Nauru'],
             ['es', $i++, 'Nepal'],
             ['es', $i++, 'Países Bajos'],
             ['es', $i++, 'Nueva Zelanda'],
             ['es', $i++, 'Nicaragua'],
             ['es', $i++, 'Níger'],
             ['es', $i++, 'Nigeria'],
             ['es', $i++, 'Noruega'],
             ['es', $i++, 'Omán'],
             ['es', $i++, 'Pakistán'],
             ['es', $i++, 'Palau'],
             ['es', $i++, 'Palestina'],
             ['es', $i++, 'Panamá'],
             ['es', $i++, 'Papúa Nueva Guinea'],
             ['es', $i++, 'Paraguay'],
             ['es', $i++, 'Perú'],
             ['es', $i++, 'Filipinas'],
             ['es', $i++, 'Polonia'],
             ['es', $i++, 'Portugal'],
             ['es', $i++, 'Katar'],
             ['es', $i++, 'Rumania'],
             ['es', $i++, 'Rusia'],
             ['es', $i++, 'Ruanda'],
             ['es', $i++, 'San Cristóbal y Nieves'],
             ['es', $i++, 'Santa Lucía'],
             ['es', $i++, 'San Vicente y las Granadinas'],
             ['es', $i++, 'Samoa'],
             ['es', $i++, 'San Marino'],
             ['es', $i++, 'Santo Tomé y Príncipe'],
             ['es', $i++, 'Arabia Saudita'],
             ['es', $i++, 'Senegal'],
             ['es', $i++, 'Serbia'],
             ['es', $i++, 'Seychelles'],
             ['es', $i++, 'Sierra Leona'],
             ['es', $i++, 'Singapur'],
             ['es', $i++, 'Eslovaquia'],
             ['es', $i++, 'Eslovenia'],
             ['es', $i++, 'Islas Salomón'],
             ['es', $i++, 'Somalia'],
             ['es', $i++, 'Sudáfrica'],
             ['es', $i++, 'Sudán del Sur'],
             ['es', $i++, 'España'],
             ['es', $i++, 'Sri Lanka'],
             ['es', $i++, 'Sudán'],
             ['es', $i++, 'Suriname'],
             ['es', $i++, 'Swazilandia'],
             ['es', $i++, 'Suecia'],
             ['es', $i++, 'Suiza'],
             ['es', $i++, 'Siria'],
             ['es', $i++, 'Tayikistán'],
             ['es', $i++, 'Tanzania'],
             ['es', $i++, 'Tailandia'],
             ['es', $i++, 'Ir'],
             ['es', $i++, 'Tonga'],
             ['es', $i++, 'Trinidad y Tobago'],
             ['es', $i++, 'Túnez'],
             ['es', $i++, 'Turquía'],
             ['es', $i++, 'Turkmenistán'],
             ['es', $i++, 'Tuvalu'],
             ['es', $i++, 'Uganda'],
             ['es', $i++, 'Ucrania'],
             ['es', $i++, 'Emiratos Árabes Unidos'],
             ['es', $i++, 'Reino Unido'],
             ['es', $i++, 'Estados Unidos'],
             ['es', $i++, 'Uruguay'],
             ['es', $i++, 'Uzbekistán'],
             ['es', $i++, 'Vanuatu'],
             ['es', $i++, 'Ciudad del Vaticano'],
             ['es', $i++, 'Venezuela'],
             ['es', $i++, 'Vietnam'],
             ['es', $i++, 'Yemen'],
             ['es', $i++, 'Zambia'],
             ['es', $i++, 'Zimbabue']
        ]);
        $i = $afghan_id;
        $this->batchInsert('country_translation', ['language_code', 'country_id', 'translation'], [
            ['de', $i++, 'Afghanistan'],
            ['de', $i++, 'Albanien'],
            ['de', $i++, 'Algerien'],
            ['de', $i++, 'Andorra'],
            ['de', $i++, 'Angola'],
            ['de', $i++, 'Antigua und Barbuda'],
            ['de', $i++, 'Argentinien'],
            ['de', $i++, 'Armenien'],
            ['de', $i++, 'Australien'],
            ['de', $i++, 'Österreich'],
            ['de', $i++, 'Aserbaidschan'],
            ['de', $i++, 'Bahamas, Die'],
            ['de', $i++, 'Bahrain'],
            ['de', $i++, 'Bangladesch'],
            ['de', $i++, 'Barbados'],
            ['de', $i++, 'Weißrussland'],
            ['de', $i++, 'Belgien'],
            ['de', $i++, 'Belize'],
            ['de', $i++, 'Benin'],
            ['de', $i++, 'Bhutan'],
            ['de', $i++, 'Bolivien'],
            ['de', $i++, 'Bosnien und Herzegowina'],
            ['de', $i++, 'Botswana'],
            ['de', $i++, 'Brasilien'],
            ['de', $i++, 'Brunei'],
            ['de', $i++, 'Bulgarien'],
            ['de', $i++, 'Burkina Faso'],
            ['de', $i++, 'Burundi'],
            ['de', $i++, 'Kambodscha'],
            ['de', $i++, 'Kamerun'],
            ['de', $i++, 'Kanada'],
            ['de', $i++, 'Kap Verde'],
            ['de', $i++, 'Zentralafrikanische Republik'],
            ['de', $i++, 'Tschad'],
            ['de', $i++, 'Chile'],
            ['de', $i++, 'China'],
            ['de', $i++, 'Kolumbien'],
            ['de', $i++, 'Komoren'],
            ['de', $i++, 'Demokratische Republik Kongo'],
            ['de', $i++, 'Kongo, Republik der Bundesrepublik Deutschland'],
            ['de', $i++, 'Costa Rica'],
            ['de', $i++, 'Kroatien'],
            ['de', $i++, 'Kuba'],
            ['de', $i++, 'Zypern'],
            ['de', $i++, 'Tschechien'],
            ['de', $i++, 'Dänemark'],
            ['de', $i++, 'Dschibuti'],
            ['de', $i++, 'Dominica'],
            ['de', $i++, 'Dominikanische Republik'],
            ['de', $i++, 'Osttimor'],
            ['de', $i++, 'Ecuador'],
            ['de', $i++, 'Ägypten'],
            ['de', $i++, 'El Salvador'],
            ['de', $i++, 'Äquatorialguinea'],
            ['de', $i++, 'Eritrea'],
            ['de', $i++, 'Estland'],
            ['de', $i++, 'Äthiopien'],
            ['de', $i++, 'Fidschi'],
            ['de', $i++, 'Finnland'],
            ['de', $i++, 'Frankreich'],
            ['de', $i++, 'Gabun'],
            ['de', $i++, 'Gambia, The'],
            ['de', $i++, 'Georgia'],
            ['de', $i++, 'Deutschland'],
            ['de', $i++, 'Ghana'],
            ['de', $i++, 'Griechenland'],
            ['de', $i++, 'Grenada'],
            ['de', $i++, 'Guatemala'],
            ['de', $i++, 'Guinea'],
            ['de', $i++, 'Guinea-Bissau'],
            ['de', $i++, 'Guyana'],
            ['de', $i++, 'Haiti'],
            ['de', $i++, 'Honduras'],
            ['de', $i++, 'Ungarn'],
            ['de', $i++, 'Island'],
            ['de', $i++, 'Indien'],
            ['de', $i++, 'Indonesien'],
            ['de', $i++, 'Ich rannte'],
            ['de', $i++, 'Irak'],
            ['de', $i++, 'Irland'],
            ['de', $i++, 'Israel'],
            ['de', $i++, 'Italien'],
            ['de', $i++, 'Elfenbeinküste'],
            ['de', $i++, 'Jamaika'],
            ['de', $i++, 'Japan'],
            ['de', $i++, 'Jordanien'],
            ['de', $i++, 'Kasachstan'],
            ['de', $i++, 'Kenia'],
            ['de', $i++, 'Kiribati'],
            ['de', $i++, 'Korea, Nord'],
            ['de', $i++, 'Korea, Süden'],
            ['de', $i++, 'Kuwait'],
            ['de', $i++, 'Kirgisistan'],
            ['de', $i++, 'Laos'],
            ['de', $i++, 'Lettland'],
            ['de', $i++, 'Libanon'],
            ['de', $i++, 'Lesotho'],
            ['de', $i++, 'Liberia'],
            ['de', $i++, 'Libyen'],
            ['de', $i++, 'Liechtenstein'],
            ['de', $i++, 'Litauen'],
            ['de', $i++, 'Luxemburg'],
            ['de', $i++, 'Mazedonien'],
            ['de', $i++, 'Madagaskar'],
            ['de', $i++, 'Malawi'],
            ['de', $i++, 'Malaysia'],
            ['de', $i++, 'Malediven'],
            ['de', $i++, 'Mali'],
            ['de', $i++, 'Malta'],
            ['de', $i++, 'Marshallinseln'],
            ['de', $i++, 'Mauretanien'],
            ['de', $i++, 'Mauritius'],
            ['de', $i++, 'Mexiko'],
            ['de', $i++, 'Mikronesien'],
            ['de', $i++, 'Moldawien'],
            ['de', $i++, 'Monaco'],
            ['de', $i++, 'Mongolei'],
            ['de', $i++, 'Montenegro'],
            ['de', $i++, 'Marokko'],
            ['de', $i++, 'Mosambik'],
            ['de', $i++, 'Myanmar'],
            ['de', $i++, 'Namibia'],
            ['de', $i++, 'Nauru'],
            ['de', $i++, 'Nepal'],
            ['de', $i++, 'Niederlande'],
            ['de', $i++, 'Neuseeland'],
            ['de', $i++, 'Nicaragua'],
            ['de', $i++, 'Niger'],
            ['de', $i++, 'Nigeria'],
            ['de', $i++, 'Norwegen'],
            ['de', $i++, 'Oman'],
            ['de', $i++, 'Pakistan'],
            ['de', $i++, 'Palau'],
            ['de', $i++, 'Palästina'],
            ['de', $i++, 'Panama'],
            ['de', $i++, 'Papua Neu-Guinea'],
            ['de', $i++, 'Paraguay'],
            ['de', $i++, 'Peru'],
            ['de', $i++, 'Philippinen'],
            ['de', $i++, 'Polen'],
            ['de', $i++, 'Portugal'],
            ['de', $i++, 'Katar'],
            ['de', $i++, 'Rumänien'],
            ['de', $i++, 'Russland'],
            ['de', $i++, 'Ruanda'],
            ['de', $i++, 'St. Kitts und Nevis'],
            ['de', $i++, 'Saint Lucia'],
            ['de', $i++, 'St. Vincent und die Grenadinen'],
            ['de', $i++, 'Samoa'],
            ['de', $i++, 'San Marino'],
            ['de', $i++, 'São Tomé und Príncipe'],
            ['de', $i++, 'Saudi Arabien'],
            ['de', $i++, 'Senegal'],
            ['de', $i++, 'Serbien'],
            ['de', $i++, 'Seychellen'],
            ['de', $i++, 'Sierra Leone'],
            ['de', $i++, 'Singapur'],
            ['de', $i++, 'Slowakei'],
            ['de', $i++, 'Slowenien'],
            ['de', $i++, 'Salomon-Inseln'],
            ['de', $i++, 'Somalia'],
            ['de', $i++, 'Südafrika'],
            ['de', $i++, 'Südsudan'],
            ['de', $i++, 'Spanien'],
            ['de', $i++, 'Sri Lanka'],
            ['de', $i++, 'Sudan'],
            ['de', $i++, 'Surinam'],
            ['de', $i++, 'Swasiland'],
            ['de', $i++, 'Schweden'],
            ['de', $i++, 'Schweiz'],
            ['de', $i++, 'Syrien'],
            ['de', $i++, 'Tadschikistan'],
            ['de', $i++, 'Tansania'],
            ['de', $i++, 'Thailand'],
            ['de', $i++, 'Gehen'],
            ['de', $i++, 'Tonga'],
            ['de', $i++, 'Trinidad und Tobago'],
            ['de', $i++, 'Tunesien'],
            ['de', $i++, 'Truthahn'],
            ['de', $i++, 'Turkmenistan'],
            ['de', $i++, 'Tuvalu'],
            ['de', $i++, 'Uganda'],
            ['de', $i++, 'Ukraine'],
            ['de', $i++, 'Vereinigte Arabische Emirate'],
            ['de', $i++, 'Großbritannien'],
            ['de', $i++, 'Vereinigte Staaten'],
            ['de', $i++, 'Uruguay'],
            ['de', $i++, 'Usbekistan'],
            ['de', $i++, 'Vanuatu'],
            ['de', $i++, 'Vatikanstadt'],
            ['de', $i++, 'Venezuela'],
            ['de', $i++, 'Vietnam'],
            ['de', $i++, 'Jemen'],
            ['de', $i++, 'Sambia'],
            ['de', $i++, 'Simbabwe']
        ]);
    }
    public function safeDown() {
        $this->dropTable('group_question');
        $this->dropTable('group_translation');
        $this->dropTable('grp');
        $this->dropTable('answer');
        $this->dropTable('question_translation');
        $this->dropTable('question');
        $this->dropTable('survey');
        $this->dropTable('department_translation');
        $this->dropTable('department');
        $this->dropTable('touroperator');
        $this->dropTable('country_translation');
        $this->dropTable('country');
        $this->dropTable('election_translation');
        $this->dropTable('election');
        $this->dropTable('met_expectation_translation');
        $this->dropTable('met_expectation');
        $this->dropTable('evolution_translation');
        $this->dropTable('evolution');
        $this->dropTable('language');
    }
}
